### ISSUE TITLE
Add ability to exclude certain instances from being blacklisted by the synchronization

### ISSUE THREAD

**Issue by Ategon** [RikudouSage/FediseerGUI#14]
Currently in the blacklist syncronization when I add endorsed instances in there to pull blocks from, there can be a community that is blocked that I dont want blocked (e.g. due to rule change in the blocked instance but not everyone has updated their censures accordingly yet)

Adding an input field where you can put domains to ignore for the blacklist would prevent that

**Comment by RikudouSage** [comment]
Fixed by #28
