### ISSUE TITLE
Censured list undefined error

### ISSUE THREAD

**Issue by wertercatt** [RikudouSage/FediseerGUI#16]
Going to https://gui.fediseer.com/instances/censured and clicking the 'Filter' button without typing anything into the text field causes an error message saying "Error There was an api error: undefined" to appear. You can keep doing this to make as many error messages appear as you desire.
![image](https://github.com/RikudouSage/FediseerGUI/assets/7116755/71823233-0f6e-4fe8-8a2f-1bf4923be877)

**Comment by RikudouSage** [comment]
@db0 That's probably caused by incorrect env variable for `FEDISEER_DEFAULT_CENSURE_LIST_FILTER_INSTANCES` - if it's empty, it does this.

**Comment by db0** [comment]
Fixed by removing erroneous quotes
