### ISSUE TITLE
API error when claiming

### ISSUE THREAD

**Issue by lazynooblet** [RikudouSage/FediseerGUI#36]
I'm trying to claim lazysoci.al but I get "The api returned this error: Internal Server Error "

**Comment by RikudouSage** [comment]
Can you tell me the admin username you were putting there?

**Comment by lazynooblet** [comment]
lazyadmin

**Comment by db0** [comment]
Please try again now

**Comment by lazynooblet** [comment]
You're really keen on this. Thanks.
Sorry, it was gone midnight for me, I had to sleep.
That worked.
